# Generated by Django 2.0.4 on 2018-04-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180420_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='confirmed',
            field=models.BooleanField(default=0),
        ),
    ]
