# Generated by Django 2.0.4 on 2018-04-20 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180420_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmeta',
            name='answer_to_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answered_to_comment_ref', to='app.Comment'),
        ),
    ]
