# Generated by Django 2.0 on 2018-06-07 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20180607_1327'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likedentity',
            unique_together={('entity', 'user')},
        ),
    ]
