# Generated by Django 2.0 on 2018-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180607_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.BooleanField(default=0),
        ),
    ]
